### ISSUE TITLE
create-drone-py-plugin doesn't work with python2?

### ISSUE THREAD

**Issue by necrolyte2** [drone/drone-python#7]
```
create-drone-py-plugin web_containers
Downloading Python Drone plugin template...
Traceback (most recent call last):
  File "/usr/local/bin/create-drone-py-plugin", line 11, in <module>
    sys.exit(main())
  File "/Library/Python/2.7/site-packages/drone/cli/plugin_creator.py", line 141, in main
    download_and_extract_template(plugin_path)
  File "/Library/Python/2.7/site-packages/drone/cli/plugin_creator.py", line 56, in download_and_extract_template
    with tempfile.TemporaryDirectory() as tmpdir_path:
AttributeError: 'module' object has no attribute 'TemporaryDirectory'
```

**Comment by gtaylor** [comment]
ah, shoot. This might help: http://stackoverflow.com/questions/19296146/tempfile-temporarydirectory-context-manager-in-python-2-7
